using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using DacpacEntityGenerator.Models;

namespace DacpacEntityGenerator.DataLayer
{
    public class GeneratedDbContext : DbContext
    {
        public GeneratedDbContext(DbContextOptions<GeneratedDbContext> options) : base(options) { }

        // DbSet properties will be generated dynamically

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Entity configuration will be generated by the generator
            // Example: Insert generated modelBuilder lines here
            // Use EntityClassGenerator.GenerateOnModelCreatingBody to generate these lines
            // modelBuilder.Entity<MyEntity>();
            // modelBuilder.Entity<MyCompositeKeyEntity>().HasKey(e => new { e.Key1, e.Key2 });
        }
    }
}
