using System.Text;
using DataManager.Core.Abstractions;
using DataManager.Core.Models.Dacpac;
using DataManager.Core.Utilities;

namespace DataManager.Infrastructure.Generation;

public class FileWriterService
{
    /// <summary>
    /// The tag written as the first line of every file produced by this generator.
    /// Used by <see cref="CleanStaleGeneratedDirectories"/> to identify generated files.
    /// </summary>
    public const string GeneratedFileTag = "// <auto-generated by DataManager - do not modify manually />";

    private readonly IGenerationLogger _logger;

    public FileWriterService(IGenerationLogger logger)
    {
        _logger = logger;
    }

    public bool WriteEntityFile(
        string outputDirectory,
        string server,
        string database,
        string schema,
        string tableName,
        string entityClassCode)
    {
        try
        {
            // Create output directory structure: ./output/{Server}/{Database}/
            var serverDir = Path.Combine(outputDirectory, server);
            var databaseDir = Path.Combine(serverDir, database);
            
            Directory.CreateDirectory(databaseDir);

            // Generate filename: {TableName}.cs (PascalCase)
            var className = NameConverter.ToPascalCase(tableName);
            var fileName = $"{className}.cs";
            var filePath = Path.Combine(databaseDir, fileName);

            // Write file with UTF-8 encoding
            File.WriteAllText(filePath, entityClassCode, Encoding.UTF8);

            // Get relative path for logging
            var relativePath = Path.GetRelativePath(outputDirectory, filePath);
            _logger.LogProgress($"[{server}].[{database}].[{schema}].[{tableName}] - Generated entity: ./output/{relativePath.Replace('\\', '/')}");

            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError($"[{server}].[{database}].[{schema}].[{tableName}] - Failed to write entity file for table {tableName}: {ex.Message}");
            return false;
        }
    }

    public void EnsureOutputDirectoryExists(string outputDirectory)
    {
        if (!Directory.Exists(outputDirectory))
        {
            Directory.CreateDirectory(outputDirectory);
            _logger.LogInfo($"Created output directory: {outputDirectory}");
        }
    }

    /// <summary>
    /// Surgically removes only the subdirectories the generator will recreate:
    /// the <c>Configuration</c> folder and one folder per server name. All other
    /// content in <paramref name="outputDirectory"/> is left untouched.
    /// </summary>
    public void CleanGeneratedDirectories(string outputDirectory, IReadOnlyList<string> serverNames)
    {
        if (!Directory.Exists(outputDirectory))
            return;

        var configDir = Path.Combine(outputDirectory, "Configuration");
        if (Directory.Exists(configDir))
        {
            Directory.Delete(configDir, true);
            _logger.LogInfo($"Cleaned configuration directory: {configDir}");
        }

        foreach (var server in serverNames)
        {
            var serverDir = Path.Combine(outputDirectory, server);
            if (Directory.Exists(serverDir))
            {
                Directory.Delete(serverDir, true);
                _logger.LogInfo($"Cleaned server directory: {serverDir}");
            }
        }
    }

    /// <summary>
    /// Deletes the specified files if they exist. Used to remove root-level
    /// generated files (e.g. DbContext .cs files) before regeneration.
    /// </summary>
    public void CleanGeneratedFiles(params string[] filePaths)
    {
        foreach (var filePath in filePaths)
        {
            if (File.Exists(filePath))
            {
                File.Delete(filePath);
                _logger.LogInfo($"Cleaned generated file: {filePath}");
            }
        }
    }

    /// <summary>
    /// Scans top-level server subdirectories in <paramref name="outputDirectory"/>
    /// (skipping <c>Configuration/</c>, which is handled by
    /// <see cref="CleanGeneratedDirectories"/>) and removes any that contain
    /// exclusively <c>.cs</c> files marked with <see cref="GeneratedFileTag"/>.
    /// Directories that contain a mix of generated and non-generated files are
    /// left intact and a warning is logged.
    /// </summary>
    public void CleanStaleGeneratedDirectories(string outputDirectory)
    {
        if (!Directory.Exists(outputDirectory))
            return;

        foreach (var dir in Directory.EnumerateDirectories(outputDirectory))
        {
            if (Path.GetFileName(dir).Equals("Configuration", StringComparison.OrdinalIgnoreCase))
                continue;

            var csFiles = Directory.EnumerateFiles(dir, "*.cs", SearchOption.AllDirectories).ToList();

            if (csFiles.Count == 0)
                continue;

            var generatedCount = csFiles.Count(IsGeneratedFile);

            if (generatedCount == csFiles.Count)
            {
                Directory.Delete(dir, true);
                _logger.LogInfo($"Removed stale generated directory: {dir}");
            }
            else
            {
                _logger.LogWarning(
                    $"Skipped stale-folder cleanup for '{Path.GetFileName(dir)}': " +
                    $"contains {csFiles.Count - generatedCount} non-generated .cs file(s).");
            }
        }
    }

    private static bool IsGeneratedFile(string filePath)
    {
        try
        {
            using var reader = new StreamReader(filePath, Encoding.UTF8);
            var firstLine = reader.ReadLine();
            return firstLine != null &&
                   firstLine.StartsWith(GeneratedFileTag, StringComparison.Ordinal);
        }
        catch
        {
            return false;
        }
    }

    public bool WriteConfigurationFile(
        string outputDirectory,
        string server,
        string database,
        string configurationClassCode)
    {
        try
        {
            // Create output directory structure: ./output/Configuration/{Server}/{Database}/
            var configDir = Path.Combine(outputDirectory, "Configuration");
            var serverDir = Path.Combine(configDir, server);
            var databaseDir = Path.Combine(serverDir, database);
            
            Directory.CreateDirectory(databaseDir);

            // Generate filename: {Database}EntityConfiguration.cs (PascalCase)
            var databasePascal = NameConverter.ToPascalCase(database);
            var fileName = $"{databasePascal}EntityConfiguration.cs";
            var filePath = Path.Combine(databaseDir, fileName);

            // Write file with UTF-8 encoding
            File.WriteAllText(filePath, configurationClassCode, Encoding.UTF8);

            // Get relative path for logging
            var relativePath = Path.GetRelativePath(outputDirectory, filePath);
            _logger.LogProgress($"[{server}].[{database}] - Generated configuration: ./output/{relativePath.Replace('\\', '/')}");

            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError($"[{server}].[{database}] - Failed to write configuration file: {ex.Message}");
            return false;
        }
    }

    public bool WriteDbContextFile(
        string outputDirectory,
        string dbContextCode)
    {
        try
        {
            // Create output directory structure: ./output/
            Directory.CreateDirectory(outputDirectory);

            // Generate filename: SQLDbContext.cs
            var fileName = "SQLDbContext.cs";
            var filePath = Path.Combine(outputDirectory, fileName);

            // Write file with UTF-8 encoding
            File.WriteAllText(filePath, dbContextCode, Encoding.UTF8);

            // Get relative path for logging
            var relativePath = Path.GetRelativePath(outputDirectory, filePath);
            _logger.LogProgress($"Generated DbContext: ./output/{relativePath.Replace('\\', '/')}");

            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError($"Failed to write DbContext file: {ex.Message}");
            return false;
        }
    }

    /// <summary>
    /// Writes <paramref name="code"/> to an exact file path specified by the
    /// caller.  Parent directories are created automatically.
    /// </summary>
    public bool WriteToPath(string filePath, string code)
    {
        try
        {
            var dir = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(filePath, code, Encoding.UTF8);
            _logger.LogProgress($"Generated: {filePath}");
            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError($"Failed to write file '{filePath}': {ex.Message}");
            return false;
        }
    }

    /// <summary>
    /// Writes a SQLite EF Core configuration file for a server/database pair.
    /// Output path: <c>{outputDirectory}/Configuration/{Server}/{Database}/SQLite/{Database}SQLiteEntityConfiguration.cs</c>
    /// </summary>
    public bool WriteSQLiteConfigurationFile(
        string outputDirectory,
        string server,
        string database,
        string configurationClassCode)
    {
        try
        {
            var configDir   = Path.Combine(outputDirectory, "Configuration");
            var serverDir   = Path.Combine(configDir, server);
            var databaseDir = Path.Combine(serverDir, database);
            var sqliteDir   = Path.Combine(databaseDir, "SQLite");

            Directory.CreateDirectory(sqliteDir);

            var databasePascal = NameConverter.ToPascalCase(database);
            var fileName   = $"{databasePascal}SQLiteEntityConfiguration.cs";
            var filePath   = Path.Combine(sqliteDir, fileName);

            File.WriteAllText(filePath, configurationClassCode, Encoding.UTF8);

            var relativePath = Path.GetRelativePath(outputDirectory, filePath);
            _logger.LogProgress($"[{server}].[{database}] - Generated SQLite configuration: ./output/{relativePath.Replace('\\', '/')}");

            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError($"[{server}].[{database}] - Failed to write SQLite configuration file: {ex.Message}");
            return false;
        }
    }
}
